book_info:
  title: "Colloquial French"
  subtitle: "The Complete Course for Beginners"
  authors: ["Valérie Demouy", "Alan Moys"]
  type: "language_textbook"
  language: "french"
  publisher: "Routledge"
  edition: "3rd"
  isbn:
    - "978-0-415-34013-7 (pbk)"
    - "978-0-415-34014-4 (audio CDs)"
    - "978-0-415-43163-7 (pack)"
    - "978-1-315-74144-4 (eBook Pack)"

section_patterns:
  unit: "Unit \d+"
  dialogue: "Dialogues"
  exercise: "Exercises"
  language_points: "Language points"
  cultural_points: "cultural points"
  pronunciation_guide: "Pronunciation guide"
  reference_grammar: "Reference grammar"
  key_to_exercises: "Key to exercises"
  glossary: "French-English glossary"
  grammar_index: "Grammar index"
  topic_index: "Topic and functions index"

formatting_rules:
  preserve_bold: true
  preserve_italics: true
  heading_levels:
    unit: 2
    dialogue: 3
    exercise: 3
    language_points: 3
    cultural_points: 3
  bold_terms: ["UN", "UNE", "LE", "LA", "Language points", "Exercises"]
  italic_terms: ["Colloquial French"]

reference_patterns:
  cd_tracks: "\(CD \d+;\s*\d+\)"
  page_numbers: "\d+"

special_sections:
  - "Did you notice"
  - "Grammar rules"
  - "Vocabulary"
  - "Acknowledgements"
  - "Introduction"
  - "How is the course organised?"
  - "What is in a unit?"
  - "The recordings and how to work with them"
  - "General learning tips"

structure_rules:
  unit_layout:
    - "Dialogues"
    - "Language points"
    - "Exercises"
    - "cultural points"
    - "short texts"